// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Administrator {

	private String nume;

	private Client client;

	public void afisare() {
	}

	public void preluareClient() {
	}

	public void creazaComanda() {
	}

	public void calculareDistanta() {
	}

	public void calculareTaxe() {
	}
};
