// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Client extends Persoana{
	
	private Comanda comanda;
	
	public Persoana persoana;

	public void afisare() {
	}

	public void plateste() {
	}
};
