// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Client extends Persoana{
	
	private Comanda comanda;
	private boolean platita;
	
	public Client() {
		super();
		this.comanda = null;
		this.platita = false;
	}
	
	public Client(Locatie locatie, String nume, String contact) {
		super(locatie, nume, contact);
		this.comanda = null;
	}
	
	public void afisare() {
		super.afisare();
		System.out.println("");
	}

	public boolean plateste() {
		this.comanda.marcheazaPlatita();
		this.platita = true;
		return true;
	}
	
	public void primesteComanda(Comanda comanda) {
		this.comanda = new Comanda();
		this.comanda = comanda;
	}
	
	public Comanda getComanda() {
		return this.comanda;
	}
	
	public boolean verificaPlatita(){
		return platita;
	}
};
