// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Comanda {
	
	private int distanta;
	
	private int greutate;
	
	private int volum;

	private int pret;
	
	private Valuta valuta;
	
	private boolean livarata;
	
	private Client expeditor;
	
	private Persoana destinatar;

	public void calcularePret() {
	}

	public void conversieValutara() {
	}

	public void afisare() {
	}
};
