// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Curier {

	private String nume;

	private Comanda comanda;

	public void marcheazaLivrat() {
	}

	public void afisare() {
	}
};
