// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public class Locatie {

	private String tara;
	
	private String judet;
	
	private String localitate;
	
	private String strada;
	
	private String numar;

	public void afisare() {
	}
};
