// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

import java.util.ArrayList;

public class Persoana {
	
	private Locatie locatie;
	private String nume;
	private String contact;
	
	public Persoana()
	{
		this.locatie = null;
		this.nume = null;
		this.contact = null;
	}
	
	public Persoana (Locatie locatie, String nume, String contact)
	{
		this.locatie = new Locatie();
		this.locatie = locatie;
		this.nume = nume;
		this.contact = contact;
	}

	public void afisare() {

		System.out.println("Nume: " + this.nume);
		System.out.println("Contact: " + this.contact);
		System.out.println("");
		this.locatie.afisare();
		System.out.println("");
	}
	
	public Locatie transmiteLocatie()
	{
		return this.locatie;
	}
	
	public static boolean verificareDate(Locatie locatie, String nume, String contact) {
		// Lista de tari permise
		ArrayList<String> listaTari = new ArrayList<String>();
		listaTari.add("Romania");
		listaTari.add("Spania");
		listaTari.add("Regatul Unit");
		listaTari.add("Italia");
		listaTari.add("Rusia");
		listaTari.add("Elvetia");
		listaTari.add("Austria");
		
		boolean isOk = false;
		if(contact.contains("@gmail.com") && listaTari.contains(locatie.getTara())) {
			isOk = true;
		}
		return isOk;
	}
};
