// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2;

public enum Valuta {

	Euro,

	Rubla,
	
	Ron,
	
	FrancElvetian,
	
	Lira
	;
};
