// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Administrator {
	/**
	 * 
	 */
	private String Nume;
	/**
	 * 
	 */
	private Client Client;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void preluareClient() {
	}

	/**
	 * 
	 */
	public void creazaComanda() {
	}

	/**
	 * 
	 */
	public void calculareDistanta() {
	}

	/**
	 * 
	 */
	public void calculareTaxe() {
	}
};
