// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private Comanda comanda;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void plateste() {
	}
};
