// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Comanda {
	/**
	 * 
	 */
	private int Distanta;
	/**
	 * 
	 */
	private int Greutate;
	/**
	 * 
	 */
	private int Volum;
	/**
	 * 
	 */
	private int Pret;
	/**
	 * 
	 */
	private Valuta Valuta;
	/**
	 * 
	 */
	private boolean livarata;
	/**
	 * 
	 */
	private Client expeditor;
	/**
	 * 
	 */
	private Persoana destinatar;

	/**
	 * 
	 */
	public void calcularePret() {
	}

	/**
	 * 
	 */
	public void conversieValutara() {
	}

	/**
	 * 
	 */
	public void afisare() {
	}
};
