// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Curier {
	/**
	 * 
	 */
	private String Nume;
	/**
	 * 
	 */
	private Comanda Comanda;

	/**
	 * 
	 */
	public void marcheazaLivrat() {
	}

	/**
	 * 
	 */
	public void afisare() {
	}
};
