// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Locatie {
	/**
	 * 
	 */
	private String Tara;
	/**
	 * 
	 */
	private String Judet;
	/**
	 * 
	 */
	private String Localitate;
	/**
	 * 
	 */
	private String Strada;
	/**
	 * 
	 */
	private String Numar;

	/**
	 * 
	 */
	public void afisare() {
	}
};
