// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagramaDeClase;

/************************************************************/
/**
 * 
 */
public class Persoana extends Client {
	/**
	 * 
	 */
	private String Locatie;
	/**
	 * 
	 */
	private String Nume;
	/**
	 * 
	 */
	private String Contact;

	/**
	 * 
	 */
	public void afisare() {
	}
};
